# Generated by Django 5.1.1 on 2024-09-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenuLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=64)),
                ('url', models.TextField(max_length=128)),
            ],
            options={
                'verbose_name': 'Navigation menu link',
                'verbose_name_plural': 'Navigation menu links',
            },
        ),
    ]
